### ISSUE TITLE
MovePlayer() in oddmap.go will not attempt to check if a move is possible.

### ISSUE THREAD

**Issue by thatretrodev** [fisik-yum/oddmap#2]
While compiling and testing the code, I discovered that the code **WILL NOT** check if a move is possible.
To reproduce the bug, simply run the program, type "DOWN",  and then type "100".
Here's some terminal output:
```Test
0
18 0
18 0
##################X#
####################
######0########0##00
############00000000
#############0000000

18 0
Enter direction and force:
DOWN
100 
panic: runtime error: index out of range [95] with length 5

goroutine 1 [running]:
TA/oddmap.PlayerMap(0x4df43d, 0x4, 0x14, 0x4, 0xc00009e000, 0x5, 0x8, 0x12, 0x5f, 0x4dfbd6, ...)
```
After reading the source code, The bug seems to occur in the `MovePlayer()` function in `oddmap.go`.
Here's the code that I'm talking about:
```go
func (m *OddMap) MovePlayer(direction string, force int) {
	if direction == "UP" {
		m.Player.Y -= force
	} else if direction == "DOWN" {
		m.Player.Y += force
	} else if direction == "LEFT" {
		m.Player.X -= force
	} else if direction == "RIGHT" {
		m.Player.X += force
	} else {
		log.Print("ERROR: INVALID DIRECTION")
	}
	checkPlayerPosition(m)
}
```

**Comment by thatretrodev** [comment]
After looking at the code even more, I found out that the crash happens in the `PlayerMap()` function inside `mapcontrol.go`.

**Comment by fisik-yum** [comment]
> After looking at the code even more, I found out that the crash happens in the `PlayerMap()` function inside `mapcontrol.go`.

Oh, I see. All of this probably leads to checkPlayerPosition () as the culprit. While testing I found the code really, REALLY inconsistent. Hopefully we'll get it fixed.

**Comment by thatretrodev** [comment]
I think I fixed it. I'll reopen this issue if the same problem somehow happens again.
